from .distance import DistanceGraph
from .elev_gain import ElevationGainGraph
from .elev_limits import ElevationLimitsGraph
from .energy import EnergyGraph
from .performance import PerformanceGraph
from .power import PowerGraph
from .ride_rate import RideRateGraph
from .speed import SpeedGraph
from .top_speed import TopSpeedGraph